name: CI/CD Pipeline - Deploy FastAPI Model

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        pip install fastapi uvicorn joblib numpy pydantic

    - name: Lint Python code
      run: |
        pip install flake8
        flake8 api/ --max-line-length=100

    - name: Build Docker image
      run: |
        docker build -t solar-pv-api .

    - name: Run Docker container (for test purposes)
      run: |
        docker run -d -p 8000:8000 solar-pv-api
