{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "a633afee-0ac9-48aa-a22d-d86e56fb1bf7",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-03-23 22:41:16.453 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-03-23 22:41:16.568 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run C:\\Users\\cojur\\anaconda3\\envs\\thunder\\Lib\\site-packages\\ipykernel_launcher.py [ARGUMENTS]\n",
      "2025-03-23 22:41:16.584 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-03-23 22:41:16.584 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-03-23 22:41:16.584 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-03-23 22:41:16.584 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-03-23 22:41:16.587 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-03-23 22:41:16.587 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-03-23 22:41:16.588 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-03-23 22:41:16.588 Session state does not function when running a script without `streamlit run`\n",
      "2025-03-23 22:41:16.588 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-03-23 22:41:16.589 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-03-23 22:41:16.589 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-03-23 22:41:16.590 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-03-23 22:41:16.590 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-03-23 22:41:16.590 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-03-23 22:41:16.590 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-03-23 22:41:16.590 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-03-23 22:41:16.590 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-03-23 22:41:16.593 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-03-23 22:41:16.593 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-03-23 22:41:16.593 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-03-23 22:41:16.595 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-03-23 22:41:16.595 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-03-23 22:41:16.595 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-03-23 22:41:16.595 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-03-23 22:41:16.595 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-03-23 22:41:16.595 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-03-23 22:41:16.595 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-03-23 22:41:16.595 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-03-23 22:41:16.595 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-03-23 22:41:16.595 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-03-23 22:41:16.595 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-03-23 22:41:16.602 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-03-23 22:41:16.603 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-03-23 22:41:16.603 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-03-23 22:41:16.604 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-03-23 22:41:16.605 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-03-23 22:41:16.605 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-03-23 22:41:16.605 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-03-23 22:41:16.606 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-03-23 22:41:16.606 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-03-23 22:41:16.607 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-03-23 22:41:16.607 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-03-23 22:41:16.607 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-03-23 22:41:16.609 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-03-23 22:41:16.626 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-03-23 22:41:16.626 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-03-23 22:41:16.626 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-03-23 22:41:16.626 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    }
   ],
   "source": [
    "# app/streamlit_app.py\n",
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import joblib\n",
    "\n",
    "# Load model and scaler\n",
    "model = joblib.load(\"solar_pv_failure_model.pkl\")\n",
    "scaler = joblib.load(\"solar_pv_scaler.pkl\")\n",
    "\n",
    "st.title(\"🔆 Solar PV Underperformance Predictor\")\n",
    "\n",
    "st.markdown(\"Enter weather and system data below to predict underperformance:\")\n",
    "\n",
    "# User inputs\n",
    "ambient_temp = st.number_input(\"Ambient Temperature (°C)\", min_value=-10.0, max_value=60.0, value=25.0)\n",
    "module_temp = st.number_input(\"Module Temperature (°C)\", min_value=-10.0, max_value=80.0, value=30.0)\n",
    "irradiation = st.number_input(\"Irradiation (kW/m²)\", min_value=0.0, max_value=1.5, value=0.8)\n",
    "ac_power = st.number_input(\"AC Power Output (kW)\", min_value=0.0, max_value=10000.0, value=1200.0)\n",
    "hour = st.slider(\"Hour of Day\", 0, 23, 12)\n",
    "day_of_week = st.selectbox(\"Day of Week\", options=list(range(7)), format_func=lambda x: ['Mon','Tue','Wed','Thu','Fri','Sat','Sun'][x])\n",
    "month = st.slider(\"Month\", 1, 12, 5)\n",
    "is_weekend = int(day_of_week in [5, 6])\n",
    "\n",
    "# Feature calculation\n",
    "efficiency = ac_power / irradiation if irradiation > 0 else 0\n",
    "\n",
    "# Assemble input\n",
    "input_df = pd.DataFrame([[\n",
    "    ambient_temp, module_temp, irradiation, ac_power,\n",
    "    efficiency, hour, day_of_week, month, is_weekend\n",
    "]], columns=[\n",
    "    'AMBIENT_TEMPERATURE', 'MODULE_TEMPERATURE', 'IRRADIATION',\n",
    "    'AC_POWER', 'EFFICIENCY', 'hour', 'day_of_week', 'month', 'is_weekend'\n",
    "])\n",
    "\n",
    "# Scale input and predict\n",
    "scaled_input = scaler.transform(input_df)\n",
    "prediction = model.predict(scaled_input)[0]\n",
    "probability = model.predict_proba(scaled_input)[0][prediction]\n",
    "\n",
    "# Output\n",
    "st.subheader(\"📊 Prediction Result\")\n",
    "if prediction == 1:\n",
    "    st.error(f\"⚠️ System is Underperforming ({probability:.2%} confidence)\")\n",
    "else:\n",
    "    st.success(f\"✅ System is Performing Normally ({probability:.2%} confidence)\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f64740c1-a042-4688-b522-0a7ad8645e00",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
